/**
 * Curated index constituent weights — REAL NSE free-float index weights,
 * extracted from the index Fact Sheet PDFs in factsheet/ by
 * scripts/build-index-weights.py. GENERATED FILE — do not edit by hand;
 * refresh the factsheets and re-run the script after NSE rebalances.
 *
 * Factsheets publish only the TOP ~10 by weight, so the long tail of each
 * index carries no weight here (the UI shows "—"). Keyed by bare NSE
 * symbol (matches app.index_constituent.symbol).
 */
export type IndexWeight = { symbol: string; weight: number };

export const INDEX_WEIGHTS_AS_OF: Record<string, string> = {
  NIFTY50: "2026-05-29",
  NIFTYNEXT50: "2026-05-29",
  NIFTY100: "2026-05-29",
  NIFTY500: "2026-05-29",
  NIFTYMIDCAP100: "2026-05-29",
  NIFTYSMALLCAP100: "2026-05-29",
  NIFTYBANK: "2026-05-29",
  NIFTYIT: "2026-05-29",
  NIFTYAUTO: "2026-05-29",
  NIFTYFMCG: "2026-05-29",
  NIFTYPHARMA: "2026-05-29",
  NIFTYMETAL: "2026-05-29",
  NIFTYREALTY: "2026-05-29",
  NIFTYENERGY: "2026-05-29",
};

export const INDEX_WEIGHTS: Record<string, IndexWeight[]> = {
  NIFTY50: [
    { symbol: "HDFCBANK", weight: 10.56 },
    { symbol: "ICICIBANK", weight: 8.32 },
    { symbol: "RELIANCE", weight: 8.27 },
    { symbol: "BHARTIARTL", weight: 5.2 },
    { symbol: "LT", weight: 4.43 },
    { symbol: "INFY", weight: 3.77 },
    { symbol: "SBIN", weight: 3.71 },
    { symbol: "AXISBANK", weight: 3.42 },
    { symbol: "KOTAKBANK", weight: 2.62 },
    { symbol: "ITC", weight: 2.56 },
  ],
  NIFTYNEXT50: [
    { symbol: "ADANIPOWER", weight: 4.0 },
    { symbol: "DIVISLAB", weight: 3.37 },
    { symbol: "HAL", weight: 3.24 },
    { symbol: "CUMMINSIND", weight: 3.16 },
    { symbol: "TATAMOTORS", weight: 3.15 },
    { symbol: "TVSMOTOR", weight: 3.13 },
    { symbol: "VBL", weight: 2.87 },
    { symbol: "TATAPOWER", weight: 2.8 },
    { symbol: "CHOLAFIN", weight: 2.62 },
    { symbol: "MOTHERSON", weight: 2.56 },
  ],
  NIFTY100: [
    { symbol: "HDFCBANK", weight: 8.56 },
    { symbol: "ICICIBANK", weight: 6.75 },
    { symbol: "RELIANCE", weight: 6.7 },
    { symbol: "BHARTIARTL", weight: 4.22 },
    { symbol: "LT", weight: 3.6 },
    { symbol: "INFY", weight: 3.06 },
    { symbol: "SBIN", weight: 3.01 },
    { symbol: "AXISBANK", weight: 2.77 },
    { symbol: "KOTAKBANK", weight: 2.13 },
    { symbol: "ITC", weight: 2.08 },
  ],
  NIFTY500: [
    { symbol: "HDFCBANK", weight: 5.89 },
    { symbol: "ICICIBANK", weight: 4.64 },
    { symbol: "RELIANCE", weight: 4.61 },
    { symbol: "BHARTIARTL", weight: 2.9 },
    { symbol: "LT", weight: 2.47 },
    { symbol: "INFY", weight: 2.1 },
    { symbol: "SBIN", weight: 2.07 },
    { symbol: "AXISBANK", weight: 1.91 },
    { symbol: "KOTAKBANK", weight: 1.46 },
    { symbol: "ITC", weight: 1.43 },
  ],
  NIFTYMIDCAP100: [
    { symbol: "BSE", weight: 5.09 },
    { symbol: "MCX", weight: 2.26 },
    { symbol: "FEDERALBNK", weight: 2.14 },
    { symbol: "SUZLON", weight: 2.08 },
    { symbol: "GVT&D", weight: 1.92 },
    { symbol: "HEROMOTOCO", weight: 1.91 },
    { symbol: "BHEL", weight: 1.83 },
    { symbol: "INDUSINDBK", weight: 1.81 },
    { symbol: "POLICYBZR", weight: 1.74 },
    { symbol: "INDUSTOWER", weight: 1.72 },
  ],
  NIFTYSMALLCAP100: [
    { symbol: "KARURVYSYA", weight: 2.5 },
    { symbol: "SONACOMS", weight: 2.5 },
    { symbol: "NAVINFLUOR", weight: 2.41 },
    { symbol: "DELHIVERY", weight: 2.32 },
    { symbol: "PIRAMALFIN", weight: 2.13 },
    { symbol: "CDSL", weight: 2.04 },
    { symbol: "ANGELONE", weight: 2.01 },
    { symbol: "RBLBANK", weight: 1.91 },
    { symbol: "PNBHOUSING", weight: 1.78 },
    { symbol: "CAMS", weight: 1.75 },
  ],
  NIFTYBANK: [
    { symbol: "HDFCBANK", weight: 17.93 },
    { symbol: "ICICIBANK", weight: 13.63 },
    { symbol: "AXISBANK", weight: 10.28 },
    { symbol: "KOTAKBANK", weight: 9.81 },
    { symbol: "SBIN", weight: 9.07 },
    { symbol: "FEDERALBNK", weight: 6.38 },
    { symbol: "INDUSINDBK", weight: 5.4 },
    { symbol: "AUBANK", weight: 4.87 },
    { symbol: "BANKBARODA", weight: 4.47 },
    { symbol: "IDFCFIRSTB", weight: 4.27 },
  ],
  NIFTYIT: [
    { symbol: "INFY", weight: 27.08 },
    { symbol: "TCS", weight: 19.71 },
    { symbol: "TECHM", weight: 11.45 },
    { symbol: "HCLTECH", weight: 10.68 },
    { symbol: "WIPRO", weight: 7.09 },
    { symbol: "PERSISTENT", weight: 6.87 },
    { symbol: "COFORGE", weight: 6.01 },
    { symbol: "LTM", weight: 4.58 },
    { symbol: "MPHASIS", weight: 3.65 },
    { symbol: "OFSS", weight: 2.88 },
  ],
  NIFTYAUTO: [
    { symbol: "M&M", weight: 23.16 },
    { symbol: "MARUTI", weight: 14.66 },
    { symbol: "BAJAJ-AUTO", weight: 9.86 },
    { symbol: "EICHERMOT", weight: 8.4 },
    { symbol: "TMPV", weight: 7.02 },
    { symbol: "TVSMOTOR", weight: 6.71 },
    { symbol: "MOTHERSON", weight: 5.49 },
    { symbol: "HEROMOTOCO", weight: 5.42 },
    { symbol: "BHARATFORG", weight: 4.44 },
    { symbol: "ASHOKLEY", weight: 3.78 },
  ],
  NIFTYFMCG: [
    { symbol: "ITC", weight: 27.21 },
    { symbol: "HINDUNILVR", weight: 18.8 },
    { symbol: "NESTLEIND", weight: 10.03 },
    { symbol: "TATACONSUM", weight: 7.55 },
    { symbol: "VBL", weight: 7.11 },
    { symbol: "BRITANNIA", weight: 6.03 },
    { symbol: "MARICO", weight: 4.28 },
    { symbol: "GODREJCP", weight: 4.07 },
    { symbol: "UNITDSPR", weight: 3.69 },
    { symbol: "RADICO", weight: 2.71 },
  ],
  NIFTYPHARMA: [
    { symbol: "SUNPHARMA", weight: 21.43 },
    { symbol: "DIVISLAB", weight: 9.53 },
    { symbol: "DRREDDY", weight: 8.94 },
    { symbol: "CIPLA", weight: 8.87 },
    { symbol: "LUPIN", weight: 6.19 },
    { symbol: "LAURUSLABS", weight: 5.96 },
    { symbol: "TORNTPHARM", weight: 5.19 },
    { symbol: "AUROPHARMA", weight: 4.49 },
    { symbol: "GLENMARK", weight: 3.85 },
    { symbol: "ALKEM", weight: 3.62 },
  ],
  NIFTYMETAL: [
    { symbol: "TATASTEEL", weight: 17.82 },
    { symbol: "HINDALCO", weight: 16.9 },
    { symbol: "JSWSTEEL", weight: 12.42 },
    { symbol: "ADANIENT", weight: 8.72 },
    { symbol: "VEDL", weight: 6.21 },
    { symbol: "JINDALSTEL", weight: 4.63 },
    { symbol: "NATIONALUM", weight: 3.94 },
    { symbol: "APLAPOLLO", weight: 3.45 },
    { symbol: "NMDC", weight: 3.15 },
    { symbol: "SAIL", weight: 3.06 },
  ],
  NIFTYREALTY: [
    { symbol: "DLF", weight: 19.28 },
    { symbol: "PHOENIXLTD", weight: 16.82 },
    { symbol: "LODHA", weight: 13.44 },
    { symbol: "GODREJPROP", weight: 13.35 },
    { symbol: "PRESTIGE", weight: 11.75 },
    { symbol: "OBEROIRLTY", weight: 10.23 },
    { symbol: "BRIGADE", weight: 4.61 },
    { symbol: "ANANTRAJ", weight: 3.99 },
    { symbol: "ABREL", weight: 3.31 },
    { symbol: "SOBHA", weight: 3.21 },
  ],
  NIFTYENERGY: [
    { symbol: "COALINDIA", weight: 9.86 },
    { symbol: "ONGC", weight: 9.4 },
    { symbol: "RELIANCE", weight: 9.25 },
    { symbol: "NTPC", weight: 6.14 },
    { symbol: "GAIL", weight: 4.75 },
    { symbol: "POWERGRID", weight: 4.41 },
    { symbol: "SUZLON", weight: 4.18 },
    { symbol: "GVT&D", weight: 3.86 },
    { symbol: "CGPOWER", weight: 3.81 },
    { symbol: "BHEL", weight: 3.68 },
  ],
};

/** symbol → weight for an index (empty map when none curated yet). */
export function weightsForIndex(code: string): Map<string, number> {
  return new Map((INDEX_WEIGHTS[code] ?? []).map((w) => [w.symbol, w.weight]));
}
